[package]
name = "borrow_key"
version = "0.1.0-alpha.0"
edition = "2024"
authors = ["Louis <836250617@qq.com>"]
license = "MIT"
document = "https://docs.rs/borrow_key"
repository = "https://github.com/kingwingfly/borrow_key"
description = "A proc-macro to derive Borrow as well as Eq, Ord, Hash"

[lib]
# This is essencial when developing macro crates
proc-macro = true

[dependencies]
quote = { version = "1.0" }
syn = { version = "2.0" }
